steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/yk-port-for-study/test-repo/test-image:v1",
        ".",
      ]

  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/yk-port-for-study/test-repo/test-image:v1",
      ]

  # Build the container image
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "--image",
        "asia-northeast1-docker.pkg.dev/yk-port-for-study/test-repo/test-image:v1",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "asia-northeast1-docker.pkg.dev/yk-port-for-study/test-repo/test-image:v1"
